# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "master" do |master|
    config.vm.box = "ubuntu/bionic64"
    master.vm.hostname = "master"
    
    # config.vm.box_check_update = false
    # master.vm.network "forwarded_port", guest: 80, host: 8080
    master.vm.network "private_network", ip: "192.168.56.0"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "master"
      vb.memory = "512"
      vb.cpus = "1"
    end
  end
end
