# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "worker01" do |worker01|
  config.vm.box = "ubuntu/bionic64"
  config.ssh.username = 'vagrant'
  worker01.vm.hostname = "worker01"
  worker01.vm.network "forwarded_port", guest: 80, host: 8082
  worker01.vm.network "private_network", ip: "192.168.56.2"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "worker01"
      vb.memory = "2048"
      vb.cpus = "2"
      vb.linked_clone = false
    end
  end
  # config.vm.provision "shell", path: "./k8s.sh"
end
