Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true

  config.vm.define "node02" do |node02|
    node02.vm.box = "ubuntu/bionic64"
    node02.vm.hostname = "node02"

    node02.vm.network "forwarded_port", guest: 22, host: 2203, id: "ssh"
    node02.vm.network "forwarded_port", guest: 80, host: 8083
    node02.vm.network "private_network", ip: "192.168.56.3"

    node02.vm.synced_folder "./shared", "/home/vagrant/shared"

    node02.vm.provider "virtualbox" do |vb|
      vb.name = "node02"
      vb.memory = "2048"
      vb.cpus = "2"
      vb.linked_clone = false
    end
  end
end
