# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.box = "ubuntu/bionic64"
  config.vm.define "node02" do |node02|
  config.vm.synced_folder "./shared", "/home/vagrant/shared"
  # config.vm.box_version = "20241002.0.0"
  # config.ssh.username = 'vagrant'
  node02.vm.hostname = "node02"
  node02.vm.network "forwarded_port", guest: 22, host: 2203, id: "ssh"
  node02.vm.network "forwarded_port", guest: 80, host: 8083
  node02.vm.network "private_network", ip: "192.168.56.2"  
  config.vm.provider "virtualbox" do |vb|
      vb.name = "node02"
      vb.memory = "2048"
      vb.cpus = "2"
      vb.linked_clone = false
    end
  end
  # config.vm.provision "shell", path: "./k8s.sh"
end
