# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "node02" do |node02|
    config.vm.box = "ubuntu/bionic64"
    node02.vm.hostname = "node02"
    node01.vm.network "forwarded_port", guest: 22, host: 2203, id: "ssh"
    node02.vm.network "private_network", ip: "192.168.56.3"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "node02"
      vb.memory = "2048"
      vb.cpus = "2"
    end
  end
end
