# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.ssh.keep_alive = true
  config.vm.define "jammy64" do |jammy64|
  config.vm.box = "ubuntu/jammy64"
  jammy64.vm.hostname = "jammy64"
  
  jammy64.vm.network "private_network", ip: "192.168.56.6"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "jammy64"
    vb.memory = "512"
    vb.cpus = "1"
  end
end
end
