# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.ssh.keep_alive = true
  config.vm.define "xenial64" do |xenial64|
  config.vm.box = "ubuntu/xenial64"
  xenial64.vm.hostname = "xenial64"
  
  xenial64.vm.network "private_network", ip: "192.168.56.5"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "xenial64"
    vb.memory = "512"
    vb.cpus = "1"
  end
end
end
