Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true

  config.vm.define "main" do |main|
    main.vm.box = "ubuntu/bionic64"
    main.vm.hostname = "main"

    main.vm.network "forwarded_port", guest: 22, host: 2201, id: "ssh"
    main.vm.network "forwarded_port", guest: 80, host: 8081
    main.vm.network "private_network", ip: "192.168.56.1"

    main.vm.synced_folder "./shared", "/home/vagrant/shared"

    main.vm.provider "virtualbox" do |vb|
      vb.name = "main"
      vb.memory = "2048"
      vb.cpus = "2"
      vb.linked_clone = false
    end
  end
end
