# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "main" do |main|
    config.vm.box = "ubuntu/bionic64"
    main.vm.hostname = "main"
    
    # config.vm.box_check_update = false
    main.vm.network "forwarded_port", guest: 80, host: 8081
    main.vm.network "private_network", ip: "192.168.56.1"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "main"
      vb.memory = "2048"
      vb.cpus = "2"
      vb.linked_clone = false
      # vb.vmx["ethernet0.virtualdev"] = "vmxnet3"
    end
  end
end
