# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "worker02" do |worker02|
  config.vm.box = "ubuntu/bionic64"
  worker02.vm.hostname = "worker02"
  worker02.vm.network "private_network", ip: "192.168.56.2"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "worker02"
    vb.memory = "512"
    vb.cpus = "1"
  end
end
end
