# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "gitlab" do |gitlab|
    config.vm.box = "ubuntu/jammy64"
    gitlab.vm.hostname = "gitlab"
    node01.vm.network "forwarded_port", guest: 22, host: 2206, id: "ssh"
    gitlab.vm.network "private_network", ip: "192.168.56.15"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "gitlab"
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end
end
