# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "server" do |server|
    config.vm.box = "ubuntu/jammy64"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.56.8"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "server"
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end
end
