# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "aws" do |aws|
  config.vm.box = "ubuntu/jammy64"
  config.vm.synced_folder ".", "/var/ec2"
  aws.vm.hostname = "aws"
  
  aws.vm.network "private_network", ip: "192.168.56.4"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "aws"
    vb.memory = "512"
    vb.cpus = "1"
  end
end
end
