# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "ldap" do |ldap|
    config.vm.box = "ubuntu/jammy64"
    ldap.vm.hostname = "ldap"
    node01.vm.network "forwarded_port", guest: 22, host: 2208, id: "ssh"
    ldap.vm.network "private_network", ip: "192.168.56.17"
    config.vm.provider "virtualbox" do |vb|
      vb.name = "ldap"
      vb.memory = "1024"
      vb.cpus = "1"
    end
  end
end
