# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "centos7" do |centos7|
  config.vm.box = "centos/7"
  centos7.vm.hostname = "centos7"
  
  centos7.vm.network "private_network", ip: "192.168.56.4"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos7"
    vb.memory = "1024"
    vb.cpus = "2"
  end
end
end
