# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "trusty64" do |trusty64|
  config.vm.box = "ubuntu/trusty64"
  trusty64.vm.hostname = "trusty64"
  
  trusty64.vm.network "private_network", ip: "192.168.56.3"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "trusty64"
    vb.memory = "1024"
    vb.cpus = "2"
  end
end
end
