# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "jenkins" do |jenkins|
  config.vm.box = "gusztavvargadr/ubuntu-server"
  jenkins.vm.hostname = "jenkins"
  jenkins.vm.network "private_network", ip: "192.168.56.8" #, guest: 8080, host: 8080
  config.vm.provider "virtualbox" do |vb|
    vb.name = "jenkins"
    vb.memory = "2048"
    vb.cpus = "1"
  end
end
end
