# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  config.vm.define "worker01" do |worker01|
  config.vm.box = "ubuntu/bionic64"
  worker01.vm.hostname = "worker01"
  worker01.vm.network "private_network", ip: "192.168.56.1"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "worker01"
    vb.memory = "512"
    vb.cpus = "1"
  end
end
end
